# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Grapher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
  # Pods for Grapher

end
