include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Grapher
Grapher_FILES = Grapher.xm
Grapher_FRAMEWORKS = Foundation UIKit IOKit
Grapher_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/tweak.mk
include $(THEOS)/makefiles/aggregate.mk